# Generated by Django 6.0.2 on 2026-02-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('father', models.CharField(max_length=255)),
                ('nummber', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
