# Generated by Django 6.0.2 on 2026-02-18 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loggin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='nummber',
            new_name='number',
        ),
    ]
